all:
	pandoc .\README.md -s --highlight-style=you.theme --reference-doc=template.docx -o output.docx
	C:\ProgramData\anaconda3\condabin\conda run -n base python C:\Users\zuoyuan\Desktop\embedded-tutorial\stm32-heart-monitor\md2docx.py